version: '3.5'

services:

  app:
    image: likesistemas/php:${VERSAO:-latest}-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
      - VERSAO=${VERSAO:-latest}
    volumes:
    - src:/var/www/
    environment:
    - INSTALL_COMPOSER=false
    - COMPOSER_INSTALL=false
    command:
    - php -v

  nginx:
    volumes:
    - src:/var/www/

volumes:
  src: