version: '3.5'
networks:
  php:
    name: php
    driver: bridge

services:

  app:
    image: likesistemas/php:${VERSAO:-latest}-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
      - VERSAO=${VERSAO:-latest}
    volumes:
    - src:/var/www/

  nginx:
    volumes:
    - src:/var/www/

volumes:
  src: